debugging

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -490,11 +490,15 @@ jobs:
         id: puppeteer-tests
         working-directory: workbench
         continue-on-error: true
-        run: npx cross-env CI=true yarn run test-electron-app
+        run: |
+          npx cross-env CI=true yarn run test-electron-app
+          echo $?
 
       - name: Binary test(s) failed
-        if: steps.selenium-tests.outcome == 'failure' || steps.puppeteer-tests-outcome == 'failure'
+        # if: steps.selenium-tests.outcome == 'failure' || steps.puppeteer-tests-outcome == 'failure'
         run: |
+          echo ${{ steps.selenium-tests.outcome }}
+          echo ${{ steps.puppeteer-tests.outcome }}
           ${{ steps.selenium-tests.outcome == 'failure' }} && echo "Selenium test failed"
           ${{ steps.puppeteer-tests.outcome == 'failure' }} && echo "Puppeteer test failed"
           exit 1
